name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate changelog
        id: changelog
        run: |
          # Get the previous tag (if any)
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREV_TAG" ]; then
            echo "No previous tag found. Showing all commits."
            git log --pretty=format:'- %h %s' > changes.txt
          else
            echo "Previous tag: $PREV_TAG"
            git log $PREV_TAG..HEAD --pretty=format:'- %h %s' > changes.txt
          fi
          echo 'changelog<<EOF' >> $GITHUB_OUTPUT
          cat changes.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            # What's Changed
            
            ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}